In [1]:
import numpy as np

In [2]:
def strided_matrix(arr, w, s):
    #formula = [((arr length - w)/s)] + 1
    #length-w gives maxx length of rows, then we divide it by strides and add 1 to get number of rows
    #using floor division (//) for getting nearest integer
    rows = (len(arr) - w) // s + 1 
    #creating a empty array
    res = [] 
    for i in range(rows):
        start = i * s
        end = start + w
        res.append(arr[start:end])
    return np.array(res)

In [3]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
w = 4
s = 2
result = strided_matrix(arr, w, s)
print(result)

[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]
